"use client";
import {useMemo,useState} from 'react';
import {BarChart3,Users,WalletCards,UserCheck,GraduationCap,MessageSquareText,ArrowUpRight,Download,CalendarRange,TrendingUp} from 'lucide-react';
import PageHeading from '../../_components/PageHeading/PageHeading';
import Drawer from '@/app/_shared/Drawer/Drawer';
import {reportCards} from '@/app/data/seedData';
import {useLmsStore} from '@/app/state/LmsStore';
import {exportCsv} from '@/app/lib/export';
import './ReportsView.css';
const icons=[BarChart3,UserCheck,WalletCards,Users,MessageSquareText,GraduationCap];
export default function ReportsView(){const{state}=useLmsStore();const[range,setRange]=useState('This Month');const[selected,setSelected]=useState(null);const summary=useMemo(()=>[{metric:'Students',value:state.students.length},{metric:'Payments',value:state.payments.length},{metric:'Messages',value:state.messages.length},{metric:'Announcements',value:state.announcements.length}], [state]);return <><PageHeading eyebrow="Reporting & insights" title="Reports" copy="Review academic, attendance, fee, admissions and communication indicators in a consistent reporting workspace." action={null} onExport={()=>exportCsv('teklms-report-summary.csv',summary)} secondary={<label className="report-range"><CalendarRange/><select value={range} onChange={e=>setRange(e.target.value)}><option>This Week</option><option>This Month</option><option>This Term</option><option>This Year</option></select></label>}/><div className="report-grid">{reportCards.map((r,i)=>{const Icon=icons[i];return <button className="portal-card report-card" key={r.id} onClick={()=>setSelected({...r,index:i})}><div className={`report-icon r-${i}`}><Icon/></div><div className="report-card-head"><span>{r.type}</span><ArrowUpRight/></div><h3>{r.title}</h3><p>{r.description}</p><div className="report-value"><strong>{r.value}</strong><small><TrendingUp/> {r.trend}</small></div></button>})}</div><div className="report-lower"><section className="portal-card report-trend"><div className="card-title"><div><b>Performance trend</b><span>{range} · academic and attendance movement</span></div></div><div className="line-chart"><div className="line-axis"><span>100</span><span>75</span><span>50</span><span>25</span></div><div className="line-columns">{[68,72,70,78,81,85,84,89,91,88,94,93].map((v,i)=><div key={i}><i style={{height:`${v}%`}}><em/></i><span>{['J','F','M','A','M','J','J','A','S','O','N','D'][i]}</span></div>)}</div></div></section><section className="portal-card report-breakdown"><div className="card-title"><div><b>Student distribution</b><span>Current enrolment by grade</span></div></div><div className="breakdown-list">{['Grade 8','Grade 9','Grade 10','Grade 11','Grade 12'].map((g,i)=>{const count=state.students.filter(s=>s.className===g).length;return <div key={g}><span>{g}</span><i><b style={{width:`${Math.min(100,count/25*100)}%`}}/></i><strong>{count}</strong></div>})}</div></section></div><Drawer open={!!selected} onClose={()=>setSelected(null)} eyebrow={`${range} report`} title={selected?.title||''}>{selected&&<ReportDetail item={selected} state={state}/>}</Drawer></>}
function ReportDetail({item,state}){const Icon=icons[item.index];const metrics=item.index===0?[['Current average','82.4%'],['Top subject','Computer Science'],['At-risk records','18'],['Course completion','76.8%']]:item.index===1?[['Institution average','94.2%'],['Above target','89%'],['Below target','11%'],['Best grade','Grade 10']]:item.index===2?[['Collected','PKR 1.25M'],['Outstanding','PKR 320K'],['Paid records',String(state.payments.filter(p=>p.status==='Paid').length)],['Open balances',String(state.payments.filter(p=>p.status==='Due').length)]]:[['Current value',item.value],['Change',item.trend],['Reporting period','Current term'],['Status','Healthy']];return <div className="report-detail"><span className={`report-detail-icon r-${item.index}`}><Icon/></span><h3>{item.title}</h3><p>{item.description} Use this view to inspect the current reporting indicators and move into the relevant workspace for record-level detail.</p><div className="report-detail-metrics">{metrics.map(([l,v])=><div key={l}><span>{l}</span><b>{v}</b></div>)}</div><button className="btn-primary" onClick={()=>exportCsv(`${item.type.toLowerCase()}-report.csv`,metrics.map(([metric,value])=>({metric,value})))}><Download/> Export report</button></div>}
