"use client";
import {useMemo,useState} from 'react';
import Image from 'next/image';
import {WalletCards,BadgeDollarSign,Clock3,ReceiptText,Search,Plus,CheckCircle2,Printer,Landmark,CreditCard,Trash2} from 'lucide-react';
import PageHeading from '../../_components/PageHeading/PageHeading';
import StatCard from '../../_components/StatCard/StatCard';
import DataTable from '../../_components/DataTable/DataTable';
import Modal from '@/app/_shared/Modal/Modal';
import Drawer from '@/app/_shared/Drawer/Drawer';
import {useLmsStore} from '@/app/state/LmsStore';
import {useToast} from '@/app/_shared/Toast/Toast';
import {exportCsv} from '@/app/lib/export';
import './AccountsView.css';
import './ReceiptPrint.css';

const money=value=>`PKR ${Number(value).toLocaleString()}`;
const pill=value=><span className={`status-pill ${value.toLowerCase()}`}>{value}</span>;

export default function AccountsView(){
 const{state,addPayment,deletePayment}=useLmsStore();
 const{toast}=useToast();
 const[tab,setTab]=useState('Overview');
 const[q,setQ]=useState('');
 const[open,setOpen]=useState(false);
 const[selected,setSelected]=useState(null);
 const[form,setForm]=useState({studentId:state.students[0]?.id||'',amount:50000,paid:50000,method:'Bank Transfer',date:'2026-09-09'});
 const total=useMemo(()=>state.payments.reduce((sum,payment)=>sum+payment.amount,0),[state.payments]);
 const collected=useMemo(()=>state.payments.reduce((sum,payment)=>sum+payment.paid,0),[state.payments]);
 const due=total-collected;
 const rows=useMemo(()=>state.payments.filter(payment=>`${payment.student} ${payment.receipt} ${payment.studentId}`.toLowerCase().includes(q.toLowerCase())),[state.payments,q]);

 const submit=event=>{event.preventDefault();const student=state.students.find(item=>item.id===form.studentId);const amount=Number(form.amount),paid=Number(form.paid);addPayment({...form,student:student?.name||'Student',amount,paid,due:Math.max(0,amount-paid),status:paid>=amount?'Paid':'Due'});setOpen(false);toast('Payment record saved and receipt created.')};
 const removePayment=payment=>{if(!confirm(`Delete receipt ${payment.receipt} for ${payment.student}?`))return;deletePayment(payment.id);if(selected?.id===payment.id)setSelected(null);toast('Payment record deleted.','success')};
 const printReceipt=()=>{document.body.classList.add('printing-receipt');const done=()=>document.body.classList.remove('printing-receipt');window.addEventListener('afterprint',done,{once:true});window.print();setTimeout(done,60000)};

 return <><PageHeading eyebrow="Finance & accounts" title="Accounts" copy="Track fee structures, collections, outstanding balances, payment methods and printable receipts." action="Record Payment" onAction={()=>setOpen(true)} onExport={()=>exportCsv('teklms-payments.csv',state.payments)}/>
  <div className="stats-grid"><StatCard icon={WalletCards} label="Fee Value" value={money(total)} meta="Recorded charges" onClick={()=>setTab('Fee Structure')}/><StatCard icon={BadgeDollarSign} label="Collected" value={money(collected)} meta={`${Math.round(collected/Math.max(1,total)*100)}% collection rate`} tone="green" onClick={()=>setTab('Payments')}/><StatCard icon={Clock3} label="Outstanding" value={money(due)} meta={`${state.payments.filter(payment=>payment.due>0).length} open balances`} tone="orange" onClick={()=>setTab('Payments')}/><StatCard icon={ReceiptText} label="Receipts" value={state.payments.length} meta="Available records" tone="violet" onClick={()=>setTab('Receipts')}/></div>
  <div className="tabs">{['Overview','Fee Structure','Payments','Receipts'].map(item=><button className={tab===item?'active':''} onClick={()=>setTab(item)} key={item}>{item}</button>)}</div>
  {tab==='Overview'&&<Overview collected={collected} due={due} total={total} payments={state.payments} setTab={setTab}/>}
  {tab==='Fee Structure'&&<FeeStructure/>}
  {(tab==='Payments'||tab==='Receipts')&&<section className="portal-card accounts-table"><div className="toolbar"><div className="toolbar-left"><label className="search-field"><Search/><input placeholder="Search student, receipt or ID" value={q} onChange={event=>setQ(event.target.value)}/></label></div><div className="toolbar-right"><span className="account-records">{rows.length} records</span></div></div><DataTable rows={rows} pageSize={11} onView={setSelected} onDelete={removePayment} columns={[{key:'receipt',label:'Receipt'},{key:'student',label:'Student'},{key:'amount',label:'Total Fee',render:money},{key:'paid',label:'Paid',render:money},{key:'due',label:'Due',render:money},{key:'method',label:'Method'},{key:'status',label:'Status',render:pill}]}/></section>}
  <Modal open={open} onClose={()=>setOpen(false)} eyebrow="Accounts" title="Record payment" footer={<><button className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" form="payment-form"><Plus/> Save Payment</button></>}><form id="payment-form" className="form-grid" onSubmit={submit}><label className="field full"><span>Student</span><select value={form.studentId} onChange={event=>setForm({...form,studentId:event.target.value})}>{state.students.map(student=><option value={student.id} key={student.id}>{student.id} · {student.name}</option>)}</select></label><label className="field"><span>Total fee</span><input type="number" min="0" value={form.amount} onChange={event=>setForm({...form,amount:event.target.value})}/></label><label className="field"><span>Amount paid</span><input type="number" min="0" value={form.paid} onChange={event=>setForm({...form,paid:event.target.value})}/></label><label className="field"><span>Payment method</span><select value={form.method} onChange={event=>setForm({...form,method:event.target.value})}><option>Bank Transfer</option><option>Card</option><option>Cash</option><option>Online</option></select></label><label className="field"><span>Payment date</span><input type="date" value={form.date} onChange={event=>setForm({...form,date:event.target.value})}/></label></form></Modal>
  <Drawer open={!!selected} onClose={()=>setSelected(null)} eyebrow="Payment receipt" title={selected?.receipt||''}>{selected&&<div className="receipt-view print-receipt"><div className="receipt-brand"><Image src="/assets/teklms-mark.svg" alt="TekLMS" width={44} height={44}/><div><b>{state.settings.institutionName||'TekLMS Academy'}</b><span>Official Payment Receipt</span></div><strong>{selected.receipt}</strong></div><div className="receipt-status"><CheckCircle2/><span>{selected.status==='Paid'?'Payment recorded':'Part payment recorded'}</span></div><div className="detail-list"><div className="detail-row"><span>Student</span><b>{selected.student}</b></div><div className="detail-row"><span>Student ID</span><b>{selected.studentId}</b></div><div className="detail-row"><span>Total fee</span><b>{money(selected.amount)}</b></div><div className="detail-row"><span>Amount paid</span><b>{money(selected.paid)}</b></div><div className="detail-row"><span>Outstanding</span><b>{money(selected.due)}</b></div><div className="detail-row"><span>Method</span><b>{selected.method}</b></div><div className="detail-row"><span>Date</span><b>{selected.date}</b></div></div><div className="receipt-print-note">Generated by TekLMS  · This receipt is valid without a signature.</div><div className="receipt-actions"><button className="btn-danger" onClick={()=>removePayment(selected)}><Trash2/> Delete</button><button className="btn-primary receipt-download" onClick={printReceipt}><Printer/> Print receipt</button></div></div>}</Drawer>
 </>;
}

function Overview({collected,due,total,payments,setTab}){const methods=['Bank Transfer','Card','Cash','Online'];const percentage=Math.round(collected/Math.max(1,total)*100);return <div className="accounts-overview"><section className="portal-card collection-card"><div className="card-title"><div><b>Collection performance</b><span>Current payment records</span></div><button onClick={()=>setTab('Payments')}>View payments</button></div><div className="collection-body"><div className="collection-ring" style={{'--value':`${percentage*3.6}deg`}}><span>{percentage}%</span><small>Collected</small></div><div className="collection-metrics"><div><span>Total fee value</span><b>{money(total)}</b></div><div><span>Collected</span><b>{money(collected)}</b></div><div><span>Outstanding</span><b>{money(due)}</b></div></div></div></section><section className="portal-card method-card"><div className="card-title"><div><b>Payment methods</b><span>Distribution by recorded payments</span></div></div><div className="method-list">{methods.map((method,index)=>{const count=payments.filter(payment=>payment.method===method).length;const pct=Math.round(count/Math.max(1,payments.length)*100);const Icon=[Landmark,CreditCard,WalletCards,BadgeDollarSign][index];return <div key={method}><span className={`method-icon m-${index}`}><Icon/></span><div><b>{method}</b><i><em style={{width:`${pct}%`}}/></i></div><strong>{pct}%</strong></div>})}</div></section></div>}
function FeeStructure(){const rows=[['Grade 8','PKR 45,000','PKR 3,000','PKR 5,000','Monthly'],['Grade 9','PKR 50,000','PKR 3,000','PKR 5,000','Monthly'],['Grade 10','PKR 55,000','PKR 3,500','PKR 6,000','Monthly'],['Grade 11','PKR 60,000','PKR 4,000','PKR 6,500','Monthly'],['Grade 12','PKR 65,000','PKR 4,000','PKR 7,000','Monthly']];return <section className="portal-card fee-structure"><div className="card-title"><div><b>Fee structure</b><span>Academic year 2026–2027</span></div><button>Edit structure</button></div><DataTable rows={rows.map((row,index)=>({id:index,grade:row[0],tuition:row[1],library:row[2],lab:row[3],cycle:row[4]}))} columns={[{key:'grade',label:'Class'},{key:'tuition',label:'Tuition'},{key:'library',label:'Library'},{key:'lab',label:'Lab'},{key:'cycle',label:'Billing Cycle'}]}/></section>}
