"use client";
import {useMemo,useState} from 'react';
import {Search,Users,GraduationCap,UserCheck,AlertCircle,Plus,Mail,Phone,MapPin,Save,Trash2,BookOpen,Check} from 'lucide-react';
import PageHeading from '../../_components/PageHeading/PageHeading';
import StatCard from '../../_components/StatCard/StatCard';
import DataTable from '../../_components/DataTable/DataTable';
import Modal from '@/app/_shared/Modal/Modal';
import Drawer from '@/app/_shared/Drawer/Drawer';
import {courses} from '@/app/data/seedData';
import {useLmsStore} from '@/app/state/LmsStore';
import {useToast} from '@/app/_shared/Toast/Toast';
import {exportCsv} from '@/app/lib/export';
import './StudentsView.css';
import './StudentsFiltersV6.css';

const pill=value=><span className={`status-pill ${String(value).toLowerCase().replaceAll(' ','-')}`}>{value}</span>;
const blank={name:'',className:'Grade 9',section:'A',email:'',phone:'',guardian:'',attendance:100,score:0,status:'Active',fee:'Paid',joined:'2026-09-09',address:'Karachi, Pakistan',courseCodes:[]};

export default function StudentsView(){
 const{state,addStudent,updateStudent,deleteStudent}=useLmsStore();
 const{toast}=useToast();
 const[q,setQ]=useState('');
 const[grade,setGrade]=useState('All');
 const[courseFilter,setCourseFilter]=useState('All');
 const[fee,setFee]=useState('All');
 const[open,setOpen]=useState(false);
 const[selected,setSelected]=useState(null);
 const[editing,setEditing]=useState(false);
 const[form,setForm]=useState(blank);
 const rows=useMemo(()=>state.students.filter(student=>(grade==='All'||student.className===grade)&&(courseFilter==='All'||(student.courseCodes||[]).includes(courseFilter))&&(fee==='All'||student.fee===fee)&&`${student.name} ${student.id} ${student.email}`.toLowerCase().includes(q.toLowerCase())),[state.students,q,grade,courseFilter,fee]);

 const startAdd=()=>{setForm({...blank,courseCodes:[]});setOpen(true)};
 const submit=event=>{event.preventDefault();if(!form.courseCodes.length)return toast('Select at least one course for this student.','info');addStudent(form);setOpen(false);toast('Student record and course enrolment added successfully.')};
 const saveEdit=event=>{event.preventDefault();if(!selected.courseCodes?.length)return toast('Select at least one course for this student.','info');updateStudent(selected.id,selected);setEditing(false);toast('Student profile and course enrolment updated.')};
 const removeStudent=student=>{if(!confirm(`Delete ${student.name}? Their portal access, notifications and live-class recipient links will also be removed.`))return;deleteStudent(student.id);if(selected?.id===student.id)setSelected(null);toast('Student record and linked portal access deleted.','success')};

 return <><PageHeading eyebrow="Student management" title="Students & Admissions" copy="Search, review and maintain student profiles, course enrolment, attendance and account standing." action="New Admission" onAction={startAdd} onExport={()=>exportCsv('teklms-students.csv',state.students)}/>
  <div className="stats-grid"><StatCard icon={Users} label="Total Students" value={state.students.length} meta="Current enrolment" onClick={()=>{setGrade('All');setCourseFilter('All');setFee('All')}}/><StatCard icon={GraduationCap} label="Grade 10" value={state.students.filter(student=>student.className==='Grade 10').length} meta="Across all sections" tone="green" onClick={()=>setGrade('Grade 10')}/><StatCard icon={AlertCircle} label="Fee Follow-up" value={state.students.filter(student=>student.fee==='Due').length} meta="Outstanding status" tone="orange" onClick={()=>setFee('Due')}/><StatCard icon={UserCheck} label="Active Records" value={state.students.filter(student=>student.status==='Active').length} meta="Currently enrolled" tone="violet" onClick={()=>{setGrade('All');setCourseFilter('All');setFee('All')}}/></div>
  <section className="portal-card students-table"><div className="toolbar"><div className="toolbar-left"><label className="search-field"><Search/><input placeholder="Search name, ID or email" value={q} onChange={event=>setQ(event.target.value)}/></label><select className="filter-select" value={grade} onChange={event=>setGrade(event.target.value)}><option>All</option>{['Grade 8','Grade 9','Grade 10','Grade 11','Grade 12'].map(value=><option key={value}>{value}</option>)}</select><select className="filter-select" value={courseFilter} onChange={event=>setCourseFilter(event.target.value)}><option value="All">All courses</option>{courses.map(course=><option value={course.code} key={course.code}>{course.title}</option>)}</select><select className="filter-select" value={fee} onChange={event=>setFee(event.target.value)}><option>All</option><option>Paid</option><option>Due</option></select></div><div className="toolbar-right"><span className="student-count">{rows.length} records</span></div></div><DataTable rows={rows} pageSize={12} onView={student=>{setSelected({...student,courseCodes:[...(student.courseCodes||[])]});setEditing(false)}} onDelete={removeStudent} columns={[{key:'id',label:'Student ID'},{key:'name',label:'Student Name'},{key:'className',label:'Class'},{key:'section',label:'Section'},{key:'courseCodes',label:'Courses',render:value=>(value||[]).length},{key:'attendance',label:'Attendance',render:value=>`${value}%`},{key:'fee',label:'Fee Status',render:pill},{key:'status',label:'Status',render:pill}]}/></section>
  <Modal open={open} onClose={()=>setOpen(false)} eyebrow="Admissions" title="Create student record" size="lg" footer={<><button className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" form="new-student" type="submit"><Plus/> Add Student</button></>}><form id="new-student" className="form-grid" onSubmit={submit}><StudentFields value={form} onChange={setForm}/></form></Modal>
  <Drawer open={!!selected} onClose={()=>{setSelected(null);setEditing(false)}} eyebrow="Student profile" title={selected?.name||''} width="560px">{selected&&<>{!editing?<div className="student-profile-drawer"><div className="student-profile-head"><span>{selected.name.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><div><h3>{selected.name}</h3><p>{selected.id} · {selected.className} — {selected.section}</p><div>{pill(selected.status)} {pill(selected.fee)}</div></div></div><div className="profile-contact"><div><Mail/><span>{selected.email}</span></div><div><Phone/><span>{selected.phone}</span></div><div><MapPin/><span>{selected.address}</span></div></div><div className="student-metrics"><div><span>Attendance</span><b>{selected.attendance}%</b><i><em style={{width:`${selected.attendance}%`}}/></i></div><div><span>Academic score</span><b>{selected.score}%</b><i><em style={{width:`${selected.score}%`}}/></i></div></div><div className="detail-list"><div className="detail-row"><span>Guardian</span><b>{selected.guardian}</b></div><div className="detail-row"><span>Joined</span><b>{selected.joined}</b></div><div className="detail-row"><span>Email</span><b>{selected.email}</b></div><div className="detail-row"><span>Phone</span><b>{selected.phone}</b></div><div className="detail-row"><span>Enrolled courses</span><b>{(selected.courseCodes||[]).map(code=>courses.find(course=>course.code===code)?.title||code).join(', ')||'None'}</b></div></div><div className="student-drawer-actions"><button className="btn-danger" onClick={()=>removeStudent(selected)}><Trash2/> Delete student</button><button className="btn-primary" onClick={()=>setEditing(true)}>Edit student profile</button></div></div>:<form className="form-grid drawer-edit-form" onSubmit={saveEdit}><StudentFields value={selected} onChange={setSelected}/><div className="drawer-edit-actions"><button type="button" className="btn-secondary" onClick={()=>setEditing(false)}>Cancel</button><button className="btn-primary"><Save/> Save Changes</button></div></form>}</>}</Drawer>
 </>;
}

function StudentFields({value,onChange}){
 const set=(key,next)=>onChange({...value,[key]:next});
 const toggleCourse=code=>set('courseCodes',(value.courseCodes||[]).includes(code)?value.courseCodes.filter(item=>item!==code):[...(value.courseCodes||[]),code]);
 return <><label className="field"><span>Full name</span><input required value={value.name} onChange={event=>set('name',event.target.value)}/></label><label className="field"><span>Email</span><input type="email" required value={value.email} onChange={event=>set('email',event.target.value)}/></label><label className="field"><span>Class</span><select value={value.className} onChange={event=>set('className',event.target.value)}>{['Grade 8','Grade 9','Grade 10','Grade 11','Grade 12'].map(option=><option key={option}>{option}</option>)}</select></label><label className="field"><span>Section</span><select value={value.section} onChange={event=>set('section',event.target.value)}><option>A</option><option>B</option><option>C</option></select></label><label className="field"><span>Phone</span><input value={value.phone} onChange={event=>set('phone',event.target.value)}/></label><label className="field"><span>Guardian</span><input value={value.guardian} onChange={event=>set('guardian',event.target.value)}/></label><label className="field"><span>Attendance %</span><input type="number" min="0" max="100" value={value.attendance} onChange={event=>set('attendance',Number(event.target.value))}/></label><label className="field"><span>Academic score %</span><input type="number" min="0" max="100" value={value.score} onChange={event=>set('score',Number(event.target.value))}/></label><label className="field"><span>Fee status</span><select value={value.fee} onChange={event=>set('fee',event.target.value)}><option>Paid</option><option>Due</option></select></label><label className="field"><span>Record status</span><select value={value.status} onChange={event=>set('status',event.target.value)}><option>Active</option><option>On Leave</option></select></label><label className="field full"><span>Address</span><input value={value.address} onChange={event=>set('address',event.target.value)}/></label><fieldset className="student-course-field full"><legend>Course enrolment</legend><p>Only these courses can target this student with live classes and learning content.</p><div>{courses.map(course=>{const active=(value.courseCodes||[]).includes(course.code);return <button type="button" className={active?'active':''} onClick={()=>toggleCourse(course.code)} key={course.code}><span>{active?<Check/>:<BookOpen/>}</span><div><b>{course.title}</b><small>{course.code}</small></div></button>})}</div></fieldset></>;
}
