"use client";
import {useCallback,useEffect,useState} from 'react';
import {Building2,Bell,ShieldCheck,SlidersHorizontal,Save,RotateCcw,Mail,Clock3,RefreshCw,CheckCircle2,AlertCircle} from 'lucide-react';
import PageHeading from '../../_components/PageHeading/PageHeading';
import {useLmsStore} from '@/app/state/LmsStore';
import {useToast} from '@/app/_shared/Toast/Toast';
import './SettingsView.css';
import './EmailDeliveryStatus.css';

export default function SettingsView(){
 const{state,updateSettings,resetWorkspace}=useLmsStore();
 const{toast}=useToast();
 const[tab,setTab]=useState('Institution');
 const[form,setForm]=useState(state.settings);
 const save=()=>{updateSettings(form);toast('Workspace settings saved.')};
 const toggle=key=>setForm(value=>({...value,[key]:!value[key]}));
 const reset=()=>{if(confirm('Reset workspace records and settings to their initial state?')){resetWorkspace();toast('Workspace restored.')}};
 return <><PageHeading eyebrow="Workspace configuration" title="Settings" copy="Manage institution details, notification delivery, operational controls and access options." action="Save Changes" onAction={save} hideExport secondary={<button className="settings-reset" onClick={reset}><RotateCcw/> Reset workspace</button>}/><div className="settings-layout"><aside className="portal-card settings-nav">{[['Institution',Building2],['Notifications',Bell],['Access',ShieldCheck],['Preferences',SlidersHorizontal]].map(([name,Icon])=><button className={tab===name?'active':''} onClick={()=>setTab(name)} key={name}><Icon/><span>{name}</span></button>)}</aside><section className="portal-card settings-panel">{tab==='Institution'&&<Institution form={form} setForm={setForm}/>} {tab==='Notifications'&&<Notifications form={form} toggle={toggle}/>} {tab==='Access'&&<Access/>}{tab==='Preferences'&&<Preferences form={form} setForm={setForm}/>}<div className="settings-save-bar"><span>Changes are saved to this workspace.</span><button className="btn-primary" onClick={save}><Save/> Save Changes</button></div></section></div></>;
}

function SectionHead({icon:Icon,title,copy}){return <div className="settings-section-head"><span><Icon/></span><div><h3>{title}</h3><p>{copy}</p></div></div>}
function Institution({form,setForm}){const set=(key,value)=>setForm({...form,[key]:value});return <><SectionHead icon={Building2} title="Institution profile" copy="Core details used across the administrative workspace."/><div className="settings-form form-grid"><label className="field full"><span>Institution name</span><input value={form.institutionName} onChange={event=>set('institutionName',event.target.value)}/></label><label className="field"><span>Academic year</span><input value={form.academicYear} onChange={event=>set('academicYear',event.target.value)}/></label><label className="field"><span>Current term</span><input value={form.term} onChange={event=>set('term',event.target.value)}/></label><label className="field full"><span>Timezone</span><select value={form.timezone} onChange={event=>set('timezone',event.target.value)}><option>Asia/Karachi</option><option>Asia/Dubai</option><option>Europe/London</option><option>America/New_York</option></select></label></div></>}
function Notifications({form,toggle}){return <><SectionHead icon={Bell} title="Notifications" copy="Choose operational alerts and verify the server-side Resend connection."/><EmailDeliveryStatus/><div className="toggle-list">{[['emailNotifications','Email notifications','Receive key workspace updates by email',Mail],['parentAlerts','Parent communication alerts','Show alerts related to parent communication',Bell],['attendanceAlerts','Attendance alerts','Highlight unusual attendance movement',Clock3],['feeReminders','Fee reminders','Surface outstanding account follow-ups',Bell],['weeklySummary','Weekly summary','Prepare a weekly operational summary',SlidersHorizontal]].map(([key,title,copy,Icon])=><Toggle key={key} icon={Icon} title={title} copy={copy} value={form[key]} onClick={()=>toggle(key)}/>)}</div></>}
function EmailDeliveryStatus(){const[status,setStatus]=useState({loading:true});const load=useCallback(()=>{setStatus(current=>({...current,loading:true}));fetch('/api/email/status',{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.message);setStatus({...data,loading:false})}).catch(error=>setStatus({loading:false,configured:false,error:error.message||'Unable to check email configuration.'}))},[]);useEffect(()=>{load()},[load]);return <div className={`email-delivery-status ${status.configured?'connected':'setup'}`}><span>{status.loading?<RefreshCw className="spin-status"/>:status.configured?<CheckCircle2/>:<AlertCircle/>}</span><div><b>{status.loading?'Checking Resend…':status.configured?'Resend connected':'Resend setup required'}</b><p>{status.error||(!status.configured?'Add RESEND_API_KEY and restart the app before testing email delivery.':`${status.mode} · From ${status.from}`)}</p>{status.configured&&<small>Delivery target: {status.recipient}</small>}</div><button type="button" onClick={load} disabled={status.loading}><RefreshCw/> Refresh</button></div>}
function Access(){return <><SectionHead icon={ShieldCheck} title="Access control" copy="Review the role structure used across TekLMS."/><div className="access-grid"><div><span>Administrator</span><b>Full workspace access</b><p>Academic, students, accounts, communication, reports and settings.</p></div><div><span>Academic Staff</span><b>Academic operations</b><p>Classes, student records, attendance, coursework and results.</p></div><div><span>Accounts Staff</span><b>Finance operations</b><p>Fee structures, payments, receipts and finance reports.</p></div><div><span>Student</span><b>Personal learning access</b><p>Assigned courses, lectures, live classes, records and fees.</p></div></div></>}
function Preferences({form,setForm}){const set=(key,value)=>setForm({...form,[key]:value});return <><SectionHead icon={SlidersHorizontal} title="Workspace preferences" copy="Set working preferences for your administrative experience."/><div className="settings-form form-grid"><label className="field"><span>Default landing view</span><select defaultValue="Dashboard"><option>Dashboard</option><option>Academic</option><option>Students</option></select></label><label className="field"><span>Rows per page</span><select defaultValue="10 rows"><option>10 rows</option><option>20 rows</option><option>50 rows</option></select></label><label className="field full"><span>Profile visibility</span><select value={form.profileVisibility?'Visible':'Limited'} onChange={event=>set('profileVisibility',event.target.value==='Visible')}><option>Visible</option><option>Limited</option></select></label></div></>}
function Toggle({icon:Icon,title,copy,value,onClick}){return <button className="setting-toggle-row" onClick={onClick}><span className="setting-row-icon"><Icon/></span><div><b>{title}</b><small>{copy}</small></div><i className={value?'on':''}><em/></i></button>}
