"use client";
import {useMemo,useState} from 'react';
import {BookOpen,CheckCircle2,Clock3,LockKeyhole,Play,Search,ShieldCheck,Video} from 'lucide-react';
import Modal from '@/app/_shared/Modal/Modal';
import SecureVideoPlayer from '@/app/_shared/SecureVideoPlayer/SecureVideoPlayer';
import {useLmsStore} from '@/app/state/LmsStore';
import './LecturesView.css';
export default function LecturesView(){
 const{state,updateLectureProgress}=useLmsStore();const[q,setQ]=useState('');const[course,setCourse]=useState('All');const[selected,setSelected]=useState(null);const assigned=state.profile?.courseCodes||[];const assignedLectures=useMemo(()=>state.lectures.filter(lecture=>lecture.audienceScope==='all'||assigned.includes(lecture.courseCode)),[state.lectures,assigned]);const courses=useMemo(()=>['All',...new Set(assignedLectures.map(lecture=>lecture.course))],[assignedLectures]);const visible=useMemo(()=>assignedLectures.filter(lecture=>(course==='All'||lecture.course===course)&&`${lecture.title} ${lecture.course}`.toLowerCase().includes(q.toLowerCase())),[assignedLectures,course,q]);const published=assignedLectures.filter(lecture=>lecture.status==='Published');const completed=published.filter(lecture=>lecture.completed).length;const current=published.find(lecture=>lecture.videoUrl&&lecture.progress>0&&!lecture.completed)||published.find(lecture=>lecture.videoUrl)||published.find(lecture=>lecture.progress>0&&!lecture.completed)||published[0];
 const open=l=>{if(l.status==='Published')setSelected(l)};
 return <div className="student-lectures"><section className="lecture-hero-student"><div><span><ShieldCheck/> Secure lecture library</span><h1>Learn at your pace, without losing your place.</h1><p>Your recorded lessons, progress and course context stay together across every subject.</p><div className="student-lecture-kpis"><div><b>{published.length}</b><span>Available lectures</span></div><div><b>{completed}</b><span>Completed</span></div><div><b>{Math.round(published.reduce((a,l)=>a+l.progress,0)/Math.max(1,published.length))}%</b><span>Average progress</span></div></div></div>{current&&<button className="continue-lecture" onClick={()=>open(current)}><span className="continue-icon"><Play/></span><div><small>Continue watching</small><b>{current.title}</b><em>{current.course} · {current.progress}% complete</em></div></button>}</section>
 <section className="student-lecture-library"><div className="student-lecture-toolbar"><div className="lecture-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search your lectures…"/></div><div className="student-course-filter">{courses.map(x=><button key={x} className={course===x?'active':''} onClick={()=>setCourse(x)}>{x}</button>)}</div></div><div className="student-lecture-grid">{visible.map(l=><button className={`student-lecture-card ${l.status==='Scheduled'?'locked':''}`} key={l.id} onClick={()=>open(l)}><div className="student-lecture-cover"><img src={l.poster} alt=""/><span className="student-lecture-shade"/>{l.status==='Published'?<span className="student-play"><Play/></span>:<span className="student-lock"><LockKeyhole/></span>}<span className="student-duration"><Clock3/> {l.duration}</span></div><div className="student-lecture-body"><div className="student-lecture-topline"><span>{l.courseCode} · Lesson {l.lesson}</span>{l.completed&&<CheckCircle2/>}</div><h3>{l.title}</h3><p>{l.description}</p><div className="student-lecture-progress"><div><i style={{width:`${l.progress}%`}}/></div><span>{l.status==='Scheduled'?'Scheduled':l.completed?'Completed':`${l.progress}%`}</span></div><footer><span><BookOpen/> {l.course}</span><b>{l.status==='Scheduled'?l.published:l.teacher}</b></footer></div></button>)}</div></section>
 <Modal open={!!selected} onClose={()=>setSelected(null)} eyebrow={selected?.course} title={selected?.title||'Lecture'} size="xl"><div className="student-player-layout">{selected&&<SecureVideoPlayer lecture={selected} identity={`${state.profile.name} · ${state.profile.id}`} onProgress={p=>updateLectureProgress(selected.id,p)}/>}<div className="watching-meta"><div><span>Lesson</span><b>{selected?.lesson}</b></div><div><span>Instructor</span><b>{selected?.teacher}</b></div><div><span>Duration</span><b>{selected?.duration}</b></div><div><span>Access</span><b><ShieldCheck/> Protected</b></div></div><p>{selected?.description}</p><div className="watching-note"><LockKeyhole/><span>Protected playback uses authenticated access, encrypted media storage, dynamic identity watermarking and focus-aware controls.</span></div></div></Modal>
 </div>
}
