"use client";
import {useMemo} from 'react';
import {EyeOff,FileKey2,KeyRound,LockKeyhole,MonitorOff,MousePointer2,Printer,ShieldCheck,ShieldEllipsis,Video} from 'lucide-react';
import PageHeading from '../../_components/PageHeading/PageHeading';
import StatCard from '../../_components/StatCard/StatCard';
import {useLmsStore} from '@/app/state/LmsStore';
import {useToast} from '@/app/_shared/Toast/Toast';
import './SecurityView.css';
const controls=[
 {key:'mediaContextProtection',icon:MousePointer2,title:'Media context protection',copy:'Blocks right-click media menus across protected images and videos.'},
 {key:'mediaDragProtection',icon:EyeOff,title:'Drag and selection protection',copy:'Prevents media dragging and direct selection inside the learning experience.'},
 {key:'shortcutProtection',icon:KeyRound,title:'Browser shortcut protection',copy:'Intercepts common save, source and developer-tool shortcuts while TekLMS is active.'},
 {key:'printProtection',icon:Printer,title:'Print protection',copy:'Hides protected content when the browser enters a print or print-to-PDF flow.'},
 {key:'capturePrivacyVeil',icon:MonitorOff,title:'Capture privacy veil',copy:'Covers protected content when supported capture shortcuts are detected.'},
 {key:'dynamicWatermarks',icon:ShieldEllipsis,title:'Dynamic identity watermarks',copy:'Keeps the signed-in learner identity visible on protected lecture playback.'}
];
export default function SecurityView(){const{state,updateSettings}=useLmsStore();const{toast}=useToast();const enabled=controls.filter(x=>state.settings[x.key]!==false).length;const encrypted=state.lectures?.filter(x=>x.secure).length||0;const logs=useMemo(()=>[
 {time:'Today · 2:18 PM',event:'Protected lecture session opened',detail:'Mathematics II · authenticated student session',level:'Allowed'},
 {time:'Today · 1:42 PM',event:'Save shortcut blocked',detail:'Protected content policy · student workspace',level:'Blocked'},
 {time:'Today · 12:06 PM',event:'Media session verified',detail:'Computer Science · lecture access granted',level:'Allowed'},
 {time:'Yesterday · 4:31 PM',event:'Focus protection engaged',detail:'Physics lecture paused when window lost focus',level:'Protected'},
 {time:'Yesterday · 11:12 AM',event:'Print flow protected',detail:'Learning content hidden before print rendering',level:'Protected'}
 ],[]);const toggle=(key)=>{updateSettings({[key]:state.settings[key]===false});toast('Content protection policy updated.','success')};return <div className="security-view"><PageHeading eyebrow="Content protection" title="Media Security" copy="Control protected lecture delivery, browser-level safeguards and identity-based content policies." action={null} hideExport secondary={<div className="security-health"><ShieldCheck/> Protection active</div>}/><div className="security-stats"><StatCard icon={ShieldCheck} label="Protection policies" value={`${enabled}/${controls.length}`} meta="Workspace safeguards enabled" tone="green"/><StatCard icon={FileKey2} label="Encrypted lectures" value={encrypted} meta="AES-256-GCM at rest" tone="blue"/><StatCard icon={LockKeyhole} label="Session access" value="Signed" meta="Authenticated media requests" tone="violet"/><StatCard icon={Video} label="Protected library" value={`${state.lectures?.length||0}`} meta="Recorded learning assets" tone="orange"/></div><section className="security-policy-panel"><header><div><b>Protection policies</b><span>Changes apply across the website and learning workspaces.</span></div><span className="policy-badge"><ShieldCheck/> {Math.round(enabled/controls.length*100)}% enabled</span></header><div className="security-control-grid">{controls.map(({key,icon:Icon,title,copy})=><button key={key} className={`security-control ${state.settings[key]===false?'off':''}`} onClick={()=>toggle(key)}><span className="security-control-icon"><Icon/></span><div><b>{title}</b><p>{copy}</p></div><span className="switch-track"><i/></span></button>)}</div></section><section className="security-bottom-grid"><article className="security-architecture"><header><b>Protected lecture pipeline</b><span>How TekLMS serves recorded content.</span></header><div className="pipeline"><div><span>1</span><div><b>Encrypted media</b><small>Lecture asset stored as AES-256-GCM ciphertext.</small></div></div><i/><div><span>2</span><div><b>Signed session</b><small>Server checks the authenticated TekLMS session.</small></div></div><i/><div><span>3</span><div><b>Protected playback</b><small>Player uses a temporary in-memory media URL and dynamic watermark.</small></div></div></div></article><article className="security-log"><header><b>Protection activity</b><span>Recent workspace events</span></header><div>{logs.map((log,i)=><div className="security-log-row" key={i}><span className={`security-log-mark ${log.level.toLowerCase()}`}><ShieldCheck/></span><div><b>{log.event}</b><small>{log.detail}</small><em>{log.time}</em></div><strong>{log.level}</strong></div>)}</div></article></section></div>}
