"use client";
import {useMemo,useState} from 'react';
import {BookOpen,CalendarClock,CheckCircle2,Clock3,Film,LockKeyhole,PlayCircle,Search,ShieldCheck,Users,Video,UploadCloud} from 'lucide-react';
import PageHeading from '../../_components/PageHeading/PageHeading';
import StatCard from '../../_components/StatCard/StatCard';
import Modal from '@/app/_shared/Modal/Modal';
import SecureVideoPlayer from '@/app/_shared/SecureVideoPlayer/SecureVideoPlayer';
import {useLmsStore} from '@/app/state/LmsStore';
import {useToast} from '@/app/_shared/Toast/Toast';
import './LecturesView.css';
const blank={title:'',course:'Mathematics II',courseCode:'MTH-201',teacher:'Ms. Hira Khan',duration:'20 min',status:'Published',audience:'Grade 10 — A',description:'',watermark:true,focusGuard:true,fileName:''};
export default function LecturesView(){
 const{state,addLecture,updateLecture}=useLmsStore();const{toast}=useToast();const[q,setQ]=useState('');const[filter,setFilter]=useState('All');const[selected,setSelected]=useState(null);const[creating,setCreating]=useState(false);const[form,setForm]=useState(blank);
 const rows=useMemo(()=>state.lectures.filter(l=>(filter==='All'||l.status===filter)&&`${l.title} ${l.course} ${l.teacher}`.toLowerCase().includes(q.toLowerCase())),[state.lectures,filter,q]);
 const published=state.lectures.filter(l=>l.status==='Published').length;const scheduled=state.lectures.filter(l=>l.status==='Scheduled').length;
 const create=e=>{e.preventDefault();addLecture({...form,lesson:state.lectures.length+1,published:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),poster:'https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1200'});setCreating(false);setForm(blank);toast('Lecture added to the library.','success')};
 const toggleStatus=(lecture,e)=>{e?.stopPropagation();const next=lecture.status==='Published'?'Scheduled':'Published';updateLecture(lecture.id,{status:next});toast(`Lecture ${next.toLowerCase()}.`,'success')};
 return <div className="lectures-admin"><PageHeading eyebrow="Learning content" title="Lectures" copy="Publish, organize and protect recorded lessons from one lecture library." action="Add Lecture" onAction={()=>setCreating(true)} hideExport secondary={<div className="lecture-security-chip"><ShieldCheck/> Protected media</div>}/>
 <div className="lecture-stats"><StatCard icon={Video} label="Lecture library" value={state.lectures.length} meta="Across active subjects" tone="green"/><StatCard icon={CheckCircle2} label="Published" value={published} meta="Available to students" tone="blue"/><StatCard icon={CalendarClock} label="Scheduled" value={scheduled} meta="Queued for release" tone="orange"/><StatCard icon={LockKeyhole} label="Protected sessions" value={`${Math.round(state.lectures.filter(l=>l.secure).length/state.lectures.length*100)}%`} meta="Encrypted media delivery" tone="violet"/></div>
 <section className="lecture-library-panel"><div className="lecture-toolbar"><div className="lecture-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search lectures, courses or instructors…"/></div><div className="lecture-filters">{['All','Published','Scheduled'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>
 <div className="admin-lecture-grid">{rows.map(l=><article className="admin-lecture-card" key={l.id} onClick={()=>setSelected(l)}><div className="lecture-cover"><img src={l.poster} alt=""/><span className="lecture-cover-shade"/><span className="lecture-play"><PlayCircle/></span><span className={`lecture-state ${l.status.toLowerCase()}`}>{l.status}</span><span className="lecture-duration"><Clock3/> {l.duration}</span></div><div className="lecture-card-body"><div className="lecture-course-line"><span>{l.courseCode}</span><b>Lesson {String(l.lesson).padStart(2,'0')}</b></div><h3>{l.title}</h3><p>{l.description}</p><div className="lecture-meta"><span><BookOpen/> {l.course}</span><span><Users/> {l.audience}</span></div><footer><div><b>{l.teacher}</b><span>{l.published}</span></div><button onClick={e=>toggleStatus(l,e)}>{l.status==='Published'?'Schedule':'Publish'}</button></footer></div></article>)}</div>{!rows.length&&<div className="empty-state"><b>No lectures found</b><p>Try a different search or status filter.</p></div>}</section>
 <Modal open={creating} onClose={()=>setCreating(false)} eyebrow="Lecture library" title="Add lecture" size="lg" footer={<><button className="btn-secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="btn-primary" form="lecture-create">Save Lecture</button></>}><form id="lecture-create" className="form-grid" onSubmit={create}><label className="field full"><span>Lecture title</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Introduction to Derivatives"/></label><label className="field"><span>Course</span><select value={form.course} onChange={e=>setForm({...form,course:e.target.value,courseCode:{'Mathematics II':'MTH-201','Physics':'PHY-210','Computer Science':'CSC-220','English Language':'ENG-205','Biology':'BIO-208'}[e.target.value]||'GEN-200'})}>{['Mathematics II','Physics','Computer Science','English Language','Biology'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Instructor</span><input value={form.teacher} onChange={e=>setForm({...form,teacher:e.target.value})}/></label><label className="field"><span>Duration</span><input value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})} placeholder="20 min"/></label><label className="field"><span>Release status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Published</option><option>Scheduled</option></select></label><label className="field full"><span>Audience</span><input value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}/></label><label className="field full"><span>Description</span><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="What will students learn in this lecture?"/></label><label className="lecture-upload full"><UploadCloud/><div><b>Lecture media</b><span>{form.fileName||'Choose an MP4 video for protected delivery'}</span></div><input type="file" accept="video/mp4,video/webm" onChange={e=>setForm({...form,fileName:e.target.files?.[0]?.name||''})}/></label><div className="protection-options full"><label><input type="checkbox" checked={form.watermark} onChange={e=>setForm({...form,watermark:e.target.checked})}/><span><ShieldCheck/><b>Dynamic identity watermark</b><small>Displays account identity during playback.</small></span></label><label><input type="checkbox" checked={form.focusGuard} onChange={e=>setForm({...form,focusGuard:e.target.checked})}/><span><LockKeyhole/><b>Focus protection</b><small>Pauses protected playback when the window loses focus.</small></span></label></div></form></Modal>
 <Modal open={!!selected} onClose={()=>setSelected(null)} eyebrow={selected?.course} title={selected?.title||'Lecture'} size="xl" footer={selected&&<><button className="btn-secondary" onClick={()=>setSelected(null)}>Close</button><button className="btn-primary" onClick={e=>toggleStatus(selected,e)}>{selected.status==='Published'?'Move to Schedule':'Publish Lecture'}</button></>}>{selected&&<div className="lecture-preview-layout"><SecureVideoPlayer lecture={selected} identity="Administrator · Content Review"/><div className="lecture-detail-grid"><div><span>Instructor</span><b>{selected.teacher}</b></div><div><span>Audience</span><b>{selected.audience}</b></div><div><span>Duration</span><b>{selected.duration}</b></div><div><span>Protection</span><b>AES-256-GCM · Session access</b></div></div><p className="lecture-preview-copy">{selected.description}</p></div>}</Modal>
 </div>
}
