"use client";
import {useState} from 'react';
import {ArrowRight,Download,WalletCards,CreditCard,Landmark,CheckCircle2,ShieldCheck} from 'lucide-react';
import Modal from '@/app/_shared/Modal/Modal';
import {useLmsStore} from '@/app/state/LmsStore';
import {useToast} from '@/app/_shared/Toast/Toast';
import './FeesView.css';
const money=v=>`PKR ${Number(v).toLocaleString()}`;
export default function FeesView(){const{state,updateBalance}=useLmsStore();const{toast}=useToast();const[open,setOpen]=useState(false);const[method,setMethod]=useState('Bank Transfer');const pay=()=>{updateBalance(0);setOpen(false);toast('Payment status updated successfully.')};return <><div className="student-page-heading"><div><span>Accounts</span><h1>My Fees</h1><p>Review your balance, fee breakdown and recent payment history.</p></div><button onClick={()=>window.print()}><Download/> Download Statement</button></div><section className="student-fee-hero"><div><span>Current balance</span><strong>{money(state.balance)}</strong><small>{state.balance>0?'Due on September 15, 2026':'No outstanding balance'}</small></div>{state.balance>0?<button onClick={()=>setOpen(true)}>Pay now <ArrowRight/></button>:<span className="balance-clear"><CheckCircle2/> Balance cleared</span>}</section><div className="fee-layout"><section className="student-card fee-breakdown"><div className="student-section-title"><b>Fee breakdown</b><span>September 2026</span></div><div className="fee-lines-v3">{[['Tuition Fee',50000],['Library Fee',3000],['Lab Fee',5000],['Scholarship',-8000]].map(([a,b])=><div key={a}><span>{a}</span><b className={b<0?'credit':''}>{b<0?'- ':''}{money(Math.abs(b))}</b></div>)}<div className="fee-total"><span>Total cycle amount</span><b>PKR 50,000</b></div></div></section><section className="student-card payment-history"><div className="student-section-title"><b>Payment history</b><span>Recent transactions</span></div>{[['Aug 15, 2026','PKR 50,000','Bank Transfer'],['Jul 15, 2026','PKR 50,000','Card'],['Jun 15, 2026','PKR 50,000','Online'],['May 15, 2026','PKR 50,000','Bank Transfer']].map((r,i)=><div className="student-payment-row" key={i}><span><WalletCards/></span><div><b>{r[1]}</b><small>{r[0]} · {r[2]}</small></div><em>Paid</em><button onClick={()=>window.print()}><Download/></button></div>)}</section></div><Modal open={open} onClose={()=>setOpen(false)} eyebrow="Secure payment" title="Pay outstanding balance" size="sm" footer={<><button className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" onClick={pay}>Confirm Payment</button></>}><div className="student-payment-modal"><div className="pay-amount"><span>Amount due</span><b>{money(state.balance)}</b></div><p>Select a payment method to continue.</p><div className="payment-methods">{[['Bank Transfer',Landmark],['Card',CreditCard],['Online',WalletCards]].map(([m,I])=><button className={method===m?'active':''} onClick={()=>setMethod(m)} key={m}><I/><span>{m}</span>{method===m&&<CheckCircle2/>}</button>)}</div><div className="payment-security"><ShieldCheck/> Your account view will update after payment confirmation.</div></div></Modal></>}
