"use client";
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {BadgeCheck,LoaderCircle,ShieldCheck,ArrowRight} from 'lucide-react';
import './ActivationPage.css';

function decodeToken(token){try{let payload=token.split('.')[0].replace(/-/g,'+').replace(/_/g,'/');payload+='='.repeat((4-payload.length%4)%4);return JSON.parse(atob(payload))}catch{return null}}
export default function ActivationPage(){const params=useSearchParams();const token=params.get('token')||'';const data=useMemo(()=>decodeToken(token),[token]);const[state,setState]=useState('working');
 useEffect(()=>{if(!data||data.type!=='approved-student'||!data.email){setState('invalid');return}try{const key='teklms-v6-approved-accounts';const legacy='teklms-v5-approved-accounts';const saved=localStorage.getItem(key)||localStorage.getItem(legacy)||'[]';const rows=JSON.parse(saved).filter(x=>x.email!==data.email);rows.unshift({email:data.email,name:data.name,studentId:data.studentId,accountToken:token,className:data.className,section:data.section,courseCodes:data.courseCodes||[],activatedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(rows));setState('ready')}catch{setState('invalid')}},[data,token]);
 return <main className="activation-page"><div className="activation-glow"/><section className="activation-card"><img src="/assets/teklms-logo.svg" alt="TekLMS"/>{state==='working'?<><LoaderCircle className="activation-spin"/><h1>Activating your account</h1><p>TekLMS is preparing your student workspace.</p></>:state==='ready'?<><span className="activation-icon"><BadgeCheck/></span><div className="activation-kicker"><ShieldCheck/> Student access enabled</div><h1>Welcome to TekLMS, {data?.name?.split(' ')[0]||'Student'}.</h1><p>Your account is ready. Sign in with <strong>{data?.email}</strong> and the password you created during registration.</p><div className="activation-meta"><span>Student ID <b>{data?.studentId}</b></span><span>Class <b>{data?.className}{data?.section?` · ${data.section}`:''}</b></span></div><a href="/login">Continue to sign in <ArrowRight/></a></>:<><span className="activation-icon error"><ShieldCheck/></span><h1>This activation link is unavailable.</h1><p>Please ask the administrator to review your registration status and issue a new account update.</p><a href="/login">Return to sign in <ArrowRight/></a></>}</section></main>}
