"use client";
import {useState} from 'react';
import {Bell,CheckCheck,ArrowRight,BookOpen,CalendarDays,WalletCards,FileText,MonitorCog,Trophy} from 'lucide-react';
import Drawer from '@/app/_shared/Drawer/Drawer';
import {useLmsStore} from '@/app/state/LmsStore';
import {useToast} from '@/app/_shared/Toast/Toast';
import './AnnouncementsView.css';
const iconMap={Academic:BookOpen,Event:CalendarDays,Fees:WalletCards,Resources:FileText,IT:MonitorCog,Sports:Trophy};
export default function AnnouncementsView(){const{state,markAnnouncementRead}=useLmsStore();const{toast}=useToast();const[filter,setFilter]=useState('All');const[selected,setSelected]=useState(null);const tags=['All',...new Set(state.announcements.map(a=>a.tag))];const rows=state.announcements.filter(a=>filter==='All'||a.tag===filter);const open=a=>{markAnnouncementRead(a.id);setSelected(a)};const markAll=()=>{state.announcements.filter(a=>!a.read).forEach(a=>markAnnouncementRead(a.id));toast('All announcements marked as read.')};return <><div className="student-page-heading"><div><span>Campus updates</span><h1>Announcements</h1><p>Important academic, account and institutional notices in one place.</p></div><button onClick={markAll}><CheckCheck/> Mark All Read</button></div><div className="announcement-filters">{tags.map(t=><button className={filter===t?'active':''} onClick={()=>setFilter(t)} key={t}>{t}</button>)}</div><div className="announcement-feed-v3">{rows.map((a,i)=>{const Icon=iconMap[a.tag]||Bell;return <button className={`student-card announcement-item-v3 ${!a.read?'unread':''}`} key={a.id} onClick={()=>open(a)}><span className={`ann-icon ai-${i%5}`}><Icon/></span><div><div className="announcement-meta"><em>{a.tag}</em><small>{a.meta}</small></div><h3>{a.title}</h3><p>{a.body}</p><b>Read announcement <ArrowRight/></b></div>{!a.read&&<i className="unread-dot"/>}</button>})}</div><Drawer open={!!selected} onClose={()=>setSelected(null)} eyebrow={selected?.tag||'Announcement'} title={selected?.title||''}>{selected&&<div className="announcement-reader"><span className="reader-icon"><Bell/></span><p>{selected.body}</p><div className="detail-list"><div className="detail-row"><span>Audience</span><b>{selected.audience}</b></div><div className="detail-row"><span>Published</span><b>{selected.meta}</b></div><div className="detail-row"><span>Category</span><b>{selected.tag}</b></div></div><button className="btn-primary" onClick={()=>setSelected(null)}>Done</button></div>}</Drawer></>}
