"use client";
import {Search,Bell,ChevronDown,Menu,LogOut,Command,CheckCheck,UserRound,Settings2,X} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {clearAuth} from '@/app/lib/auth';
import ThemeToggle from '@/app/_shared/ThemeToggle/ThemeToggle';
import {useLmsStore} from '@/app/state/LmsStore';
import './Topbar.css';
export default function Topbar({role,items,onNavigate,onMenu}){
 const[q,setQ]=useState('');const[focus,setFocus]=useState(false);const[notesOpen,setNotesOpen]=useState(false);const[userOpen,setUserOpen]=useState(false);const inputRef=useRef(null);const router=useRouter();const{state,markNotificationRead,markAllNotificationsRead}=useLmsStore();
 useEffect(()=>{const fn=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();inputRef.current?.focus()}};addEventListener('keydown',fn);return()=>removeEventListener('keydown',fn)},[]);
 const logout=async()=>{try{await fetch('/api/auth/logout',{method:'POST'})}catch{}clearAuth();router.push('/login')};
 const students=role==='admin'?state.students.filter(s=>`${s.name} ${s.id}`.toLowerCase().includes(q.toLowerCase())).slice(0,4):[];
 const modules=items.filter(i=>i.label.toLowerCase().includes(q.toLowerCase())).slice(0,5);
 const hasResults=q.trim()&&(students.length||modules.length);const visibleNotifications=state.notifications.filter(n=>role==='admin'?(n.audience||'admin')==='admin':n.audience==='student'&&(!n.studentId||n.studentId===state.profile.id));const unread=visibleNotifications.filter(n=>!n.read).length;
 const go=key=>{onNavigate?.(key);setQ('');setFocus(false)};
 return <header className="portal-topbar"><button className="top-menu" onClick={onMenu} aria-label="Open navigation"><Menu/></button><div className="top-search-wrap"><div className={`top-search ${focus?'focused':''}`}><Search/><input ref={inputRef} placeholder={role==='admin'?'Search students or workspace…':'Search your workspace…'} value={q} onChange={e=>setQ(e.target.value)} onFocus={()=>setFocus(true)} onBlur={()=>setTimeout(()=>setFocus(false),160)}/><kbd><Command/> K</kbd>{q&&<button className="clear-search" onMouseDown={e=>e.preventDefault()} onClick={()=>setQ('')}><X/></button>}</div>{focus&&q.trim()&&<div className="search-results">{hasResults? <>{modules.length>0&&<div className="search-group"><small>Workspace</small>{modules.map(m=><button key={m.key} onMouseDown={e=>e.preventDefault()} onClick={()=>go(m.key)}><Search/><span>{m.label}</span><em>Open</em></button>)}</div>}{students.length>0&&<div className="search-group"><small>Students</small>{students.map(s=><button key={s.id} onMouseDown={e=>e.preventDefault()} onClick={()=>go('students')}><span className="result-avatar">{s.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><span><b>{s.name}</b><i>{s.id} · {s.className} {s.section}</i></span><em>View</em></button>)}</div>}</>:<div className="no-search">No matching records found.</div>}</div>}</div><div className="top-actions"><ThemeToggle compact className="top-theme-toggle"/><div className="dropdown-wrap"><button className="notification" onClick={()=>{setNotesOpen(v=>!v);setUserOpen(false)}} aria-label="Notifications"><Bell/>{unread>0&&<i>{unread}</i>}</button>{notesOpen&&<div className="notification-panel"><div className="dropdown-head"><div><b>Notifications</b><span>{unread} unread</span></div><button onClick={markAllNotificationsRead}><CheckCheck/> Mark all read</button></div><div className="notification-list">{visibleNotifications.map(n=><button className={n.read?'read':''} key={n.id} onClick={()=>{markNotificationRead(n.id);onNavigate?.(n.module);setNotesOpen(false)}}><span className="note-dot"/><div><b>{n.title}</b><p>{n.detail}</p><small>{n.time}</small></div></button>)}</div></div>}</div><div className="dropdown-wrap"><button className="top-user" onClick={()=>{setUserOpen(v=>!v);setNotesOpen(false)}}><span>{role==='admin'?'AK':(state.profile?.name||'Student').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span><div><b>{role==='admin'?'Ahmed Khan':state.profile?.name||'Student'}</b><small>{role==='admin'?'Administrator':state.profile?.grade||'Student workspace'}</small></div><ChevronDown/></button>{userOpen&&<div className="user-menu"><button onClick={()=>{go(role==='admin'?'settings':'profile');setUserOpen(false)}}><UserRound/> Profile & account</button>{role==='admin'&&<button onClick={()=>{go('settings');setUserOpen(false)}}><Settings2/> Workspace settings</button>}<hr/><button onClick={logout}><LogOut/> Sign out</button></div>}</div></div></header>
}
