"use client";
import {useMemo,useState} from 'react';
import {BadgeCheck,BookOpen,Check,CheckCircle2,Clock3,Mail,Search,ShieldCheck,UserCheck,UserPlus,XCircle,Trash2} from 'lucide-react';
import PageHeading from '../../_components/PageHeading/PageHeading';
import Modal from '@/app/_shared/Modal/Modal';
import {courses} from '@/app/data/seedData';
import {useLmsStore} from '@/app/state/LmsStore';
import {useToast} from '@/app/_shared/Toast/Toast';
import './RegistrationsView.css';
import './RegistrationActions.css';

export default function RegistrationsView(){
 const{state,approveRegistration,rejectRegistration,deleteRegistration}=useLmsStore();
 const{toast}=useToast();
 const[tab,setTab]=useState('Pending');
 const[q,setQ]=useState('');
 const[review,setReview]=useState(null);
 const[loading,setLoading]=useState(false);
 const[reason,setReason]=useState('');
 const[assignment,setAssignment]=useState({classId:'',className:'',section:'',courseCodes:[]});
 const rows=useMemo(()=>state.pendingRegistrations.filter(registration=>(tab==='All'||registration.status===tab)&&`${registration.name} ${registration.email} ${registration.requestedGrade}`.toLowerCase().includes(q.toLowerCase())),[state.pendingRegistrations,tab,q]);
 const counts=['Pending','Approved','Rejected'].reduce((result,status)=>(result[status]=state.pendingRegistrations.filter(registration=>registration.status===status).length,result),{});

 const openReview=registration=>{setReview(registration);const selectedClass=state.classes.find(item=>item.name===registration.requestedGrade)||state.classes[0];setAssignment({classId:selectedClass?.id||'',className:selectedClass?.name||registration.requestedGrade,section:selectedClass?.section||'A',courseCodes:[registration.requestedCourse].filter(Boolean)});setReason('')};
 const pickClass=id=>{const selectedClass=state.classes.find(item=>item.id===id);setAssignment(current=>({...current,classId:id,className:selectedClass?.name||'',section:selectedClass?.section||''}))};
 const toggleCourse=code=>setAssignment(current=>({...current,courseCodes:current.courseCodes.includes(code)?current.courseCodes.filter(item=>item!==code):[...current.courseCodes,code]}));
 const remove=()=>{if(!review||!confirm(`Permanently delete ${review.name}'s ${review.status.toLowerCase()} registration record?`))return;deleteRegistration(review.requestId);setReview(null);toast('Registration record deleted.','success')};
 const approve=async()=>{if(!review||!assignment.className||!assignment.courseCodes.length){toast('Assign a class and at least one course.','info');return}setLoading(true);try{const highest=state.students.reduce((max,student)=>Math.max(max,Number(student.id.replace('ST-',''))||0),0);const studentId=`ST-${String(highest+1).padStart(4,'0')}`;const response=await fetch('/api/registrations/status-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'Approved',registrationToken:review.registrationToken,studentId,assignment})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Approval could not be completed.');approveRegistration(review.requestId,{assignment,accountToken:data.accountToken});setReview(null);toast(data.emailSent===false?'Student approved. Email delivery needs Resend configuration.':'Student approved and account update prepared.','success')}catch(error){toast(error.message,'error')}finally{setLoading(false)}};
 const reject=async()=>{if(!review)return;setLoading(true);try{const response=await fetch('/api/registrations/status-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'Rejected',registrationToken:review.registrationToken})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Unable to update this request.');rejectRegistration(review.requestId,reason||'Registration was not approved.');setReview(null);toast('Registration marked as rejected.','success')}catch(error){toast(error.message,'error')}finally{setLoading(false)}};
 const footer=review?.status==='Pending'?<><button className="btn-danger registration-delete" disabled={loading} onClick={remove}><Trash2/> Delete</button><button className="btn-secondary" disabled={loading} onClick={reject}><XCircle/> Reject</button><button className="btn-primary" disabled={loading} onClick={approve}><BadgeCheck/> {loading?'Saving…':'Approve & activate'}</button></>:<><button className="btn-danger registration-delete" onClick={remove}><Trash2/> Delete</button><button className="btn-primary" onClick={()=>setReview(null)}>Close</button></>;

 return <div className="registrations-view">
  <PageHeading eyebrow="Admissions" title="Student Registrations" copy="Review verified student requests, assign classes and courses, activate portal access, or delete obsolete requests."/>
  <div className="registration-stats"><button onClick={()=>setTab('Pending')}><span><Clock3/></span><div><b>{counts.Pending}</b><small>Awaiting review</small></div></button><button onClick={()=>setTab('Approved')}><span><UserCheck/></span><div><b>{counts.Approved}</b><small>Approved accounts</small></div></button><button onClick={()=>setTab('Rejected')}><span><XCircle/></span><div><b>{counts.Rejected}</b><small>Rejected requests</small></div></button><div><span><ShieldCheck/></span><div><b>Email verified</b><small>OTP checked before review</small></div></div></div>
  <section className="registration-panel"><div className="registration-toolbar"><div className="registration-tabs">{['Pending','Approved','Rejected','All'].map(status=><button key={status} className={tab===status?'active':''} onClick={()=>setTab(status)}>{status}{status!=='All'&&<i>{counts[status]||0}</i>}</button>)}</div><label><Search/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Search registrations…"/></label></div>{rows.length?<div className="registration-list">{rows.map(registration=><button className="registration-row" key={registration.requestId} onClick={()=>openReview(registration)}><span className={`registration-status ${registration.status.toLowerCase()}`}>{registration.status==='Pending'?<Clock3/>:registration.status==='Approved'?<CheckCircle2/>:<XCircle/>}</span><div className="registration-person"><b>{registration.name}</b><small>{registration.email}</small></div><div><small>Requested class</small><b>{registration.requestedGrade}</b></div><div><small>Primary course</small><b>{courses.find(course=>course.code===registration.requestedCourse)?.title||registration.requestedCourse}</b></div><div><small>Submitted</small><b>{new Date(registration.submittedAt).toLocaleDateString()}</b></div><span className="review-label">Review</span></button>)}</div>:<div className="registration-empty"><span><UserPlus/></span><h3>No {tab==='All'?'registration':tab.toLowerCase()} requests</h3><p>Verified student signup requests will appear here for academic review.</p></div>}</section>
  <Modal open={Boolean(review)} onClose={()=>!loading&&setReview(null)} eyebrow="Student registration" title={review?.name||'Review student'} size="lg" footer={footer}><div className="registration-review"><div className="registration-identity"><span>{review?.name?.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><div><h3>{review?.name}</h3><p><Mail/> {review?.email}</p><small>{review?.phone||'No phone added'} · Guardian: {review?.guardian||'Not provided'}</small></div><em className={`status-pill ${review?.status?.toLowerCase()}`}>{review?.status}</em></div><div className="registration-requested"><div><small>Requested class</small><b>{review?.requestedGrade}</b></div><div><small>Requested course</small><b>{courses.find(course=>course.code===review?.requestedCourse)?.title||review?.requestedCourse}</b></div><div><small>Email verification</small><b><Check/> Verified</b></div></div>{review?.status==='Pending'?<><div className="registration-form-block"><div><span>Academic assignment</span><h4>Choose the student’s class.</h4></div><label className="field"><span>Class & section</span><select value={assignment.classId} onChange={event=>pickClass(event.target.value)}>{state.classes.map(item=><option key={item.id} value={item.id}>{item.name} — Section {item.section} · {item.teacher}</option>)}</select></label></div><div className="registration-form-block"><div><span>Course access</span><h4>Select courses for this student.</h4></div><div className="registration-course-grid">{courses.map(course=>{const active=assignment.courseCodes.includes(course.code);return <button type="button" key={course.code} className={active?'active':''} onClick={()=>toggleCourse(course.code)}><span>{active?<Check/>:<BookOpen/>}</span><div><b>{course.title}</b><small>{course.code} · {course.teacher}</small></div></button>})}</div></div><label className="field"><span>Internal review note (used when rejecting)</span><textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Optional review note…"/></label></>:<div className="registration-result"><BadgeCheck/><div><b>{review?.status==='Approved'?'Student access activated':'Registration closed'}</b><p>{review?.status==='Approved'?`${review?.assignment?.className||''} — Section ${review?.assignment?.section||''}`:review?.reason||'This request is no longer pending.'}</p></div></div>}</div></Modal>
 </div>;
}
